### ISSUE TITLE
Import once

### ISSUE THREAD

**Issue by vladblindu** [lennym/npm-sass#19]
Hello and thank you for your work.
Is there any implemented way to "import once"? I get a lot of redundancy.
Thanks again.

**Comment by lennym** [comment]
There is, but it's out of scope for this module - I'm only interested in resolving include paths, not adding features to sass itself. 

You can see an example here:

https://github.com/alphagov/govuk-frontend/blob/master/src/tools/_exports.scss and then usage here: https://github.com/alphagov/govuk-frontend/blob/master/src/core/_template.scss#L3
