### ISSUE TITLE
Look for "sass" property in package.json

### ISSUE THREAD

**Issue by rahatarmanahmed** [lennym/npm-sass#3]
I've noticed a few SASS projects use both a `style` and `sass` property in their `package.json`'s. Seems like the `style` property points to the compiled CSS and the `sass` property points to the source SASS.

Perhaps npm-sass could look for both, prioritizing the `sass` property if it finds it?

**Comment by lennym** [comment]
Thanks for the suggestion @rahatarmanahmed. Do you have an example of a project which uses a `sass` property in package.json for me to test against?

Meanwhile, if you wanted to make a PR to the code at https://github.com/lennym/npm-sass/blob/master/lib/importer.js#L18-L20 to affect this change that would be super helpful.

**Comment by rahatarmanahmed** [comment]
Here's some examples:
- [Photon](https://github.com/connors/photon/blob/78236888ba306ee81c10b8d873e2d8ab816adce9/package.json#L12)
- [Bootstrap](https://github.com/twbs/bootstrap/blob/562d2239c0b8ef56dae04bd44eac0c419def6467/package.json#L21) (this uses less but it's the same idea)

...I could have sworn I've seen more libraries do this, but I can't seem to find them.

I still think it's a good idea, since it allows a package to give both compiled and source SASS, and npm-sass can pick up on the source when it's available. I can definitely make a PR to make it happen, I just wanted to throw the idea out there to see how well it'd be received.
