### ISSUE TITLE
Strip .css extension from npm imports to ensure files are inlined.

### ISSUE THREAD

**Issue by darkobits** [lennym/npm-sass#8]
When Sass encounters an `@import` directive where the file ends in `.css`, it compiles it into a "native" CSS `@import` with a `url()`. For example:

```css
@import "foo.css";
```

Is compiled to:

```css
@import url(foo.css);
```

Rather than having `foo.css` inlined.

This is problematic when trying to `@import` `.css` files from `node_modules`. In fact, the Bootstrap example in this repo's `README` will output a CSS file with a native `@import url(...)` containing the absolute path to `bootsrap.css` on the local machine.

This can be easily avoided by omitting the `.css` extension when you want Sass to inline the file instead, which I think should *always* be the case when importing from an NPM module.

**Comment by lennym** [comment]
Hi, and thanks for raising an issue.

I'm crazy busy at the moment I'm afraid, so might not have a chance to look into this for a few days at least, but if you were able to put together a PR then I'd be happy to merge a fix.

**Comment by lennym** [comment]
@darkobits I've finally had a chance to look into this, and it seems that this is behaviour defined in `node-sass` rather than anything that is controlled within `npm-sass`.

`npm-sass` is not able to affect how the node-sass compiler handles a request to import a `.css` file.
